wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1678415797.740473
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.4
      5: 0.13.11
      8:
      - 1
      - 5
architecture:
  desc: null
  value: regression
dataset:
  desc: null
  value: hyundaikia
features:
  desc: null
  value:
  - 3
  - 5
split:
  desc: null
  value: 20
